// @vitest-environment jsdom
import { describe, expect, it } from 'vitest'
import concertXml from '../../fixtures/sync_concert.musicxml?raw'
import hornXml from '../../fixtures/sync_horn_in_f.musicxml?raw'
import { Rational } from './rational'
import { buildSyncMap, pitchMidiByCanonical } from './syncMap'

/**
 * The committed sync fixture is generated by scripts/gen-fixtures.mjs with
 * hand-known onsets (divisions=480 → 1 ql = 480 ticks, 4 ql per bar):
 *
 *   m1  sn-1..5   @ 0, 1, 1.5, 2, 3
 *   m2  sn-6..9   @ 4, 5, 5.5, 6
 *   m3  sn-10@8, sn-11@9, sn-12@10 (dq, tie start), sn-13@11.5
 *   m4  sn-12 frag2 (h, 12–14), rest
 *   m5  sn-14..19 @ 16, 16.5, 17, 17.5, 18, 19
 *   m6  sn-20@20 (dq), sn-21@21.5, sn-22@22 (h)
 *   m7  sn-23@24, sn-24@25, sn-25@26 (h, tie start)
 *   m8  sn-25 frag2 (e, 28–28.5), sn-26@28.5, sn-27@29 (h), rest
 *   m9  sn-28..31 @ 32,33,34,35
 *   m10 sn-32@36 (h), sn-33@38, sn-34@38.5, sn-35@39
 *   m11 sn-36@40, sn-37@41, sn-38@42 (h, tie start)
 *   m12 sn-38 frag2 (q, 44–45) + frag3 (e, 45–45.5), sn-39@45.5, sn-40@46 (h)
 */

const EXPECTED_ONSETS: [string, string][] = [
  ['sn-000001', '0'], ['sn-000002', '1'], ['sn-000003', '3/2'], ['sn-000004', '2'],
  ['sn-000005', '3'], ['sn-000006', '4'], ['sn-000007', '5'], ['sn-000008', '11/2'],
  ['sn-000009', '6'], ['sn-000010', '8'], ['sn-000011', '9'], ['sn-000012', '10'],
  ['sn-000013', '23/2'], ['sn-000014', '16'], ['sn-000015', '33/2'], ['sn-000016', '17'],
  ['sn-000017', '35/2'], ['sn-000018', '18'], ['sn-000019', '19'], ['sn-000020', '20'],
  ['sn-000021', '43/2'], ['sn-000022', '22'], ['sn-000023', '24'], ['sn-000024', '25'],
  ['sn-000025', '26'], ['sn-000026', '57/2'], ['sn-000027', '29'], ['sn-000028', '32'],
  ['sn-000029', '33'], ['sn-000030', '34'], ['sn-000031', '35'], ['sn-000032', '36'],
  ['sn-000033', '38'], ['sn-000034', '77/2'], ['sn-000035', '39'], ['sn-000036', '40'],
  ['sn-000037', '41'], ['sn-000038', '42'], ['sn-000039', '91/2'], ['sn-000040', '46'],
]

function frac(s: string): Rational {
  const [n, d] = s.split('/')
  return Rational.of(BigInt(n), BigInt(d ?? 1))
}

describe('buildSyncMap (committed sync fixture)', () => {
  const map = buildSyncMap(concertXml)

  it('finds all 40 canonical notes, sorted by onset', () => {
    expect(map.spans.length).toBe(40)
    expect(map.spans.map((s) => s.canonicalId)).toEqual(EXPECTED_ONSETS.map(([id]) => id))
  })

  it('computes exact ql onsets matching the generator table', () => {
    for (const [id, ql] of EXPECTED_ONSETS) {
      const span = map.spans.find((s) => s.canonicalId === id)
      expect(span, id).toBeDefined()
      expect(span!.onsetQl.eq(frac(ql)), `${id} onset ${span!.onsetQl} != ${ql}`).toBe(true)
    }
  })

  it('merges tie fragments into one canonical span', () => {
    const sn12 = map.spans.find((s) => s.canonicalId === 'sn-000012')!
    expect(sn12.exportIds).toEqual(['hs-sn-000012', 'hs-sn-000012-2'])
    expect(sn12.onsetQl.eq(Rational.of(10))).toBe(true)
    expect(sn12.offsetQl.eq(Rational.of(14))).toBe(true) // through m4 half

    const sn38 = map.spans.find((s) => s.canonicalId === 'sn-000038')!
    expect(sn38.exportIds).toEqual(['hs-sn-000038', 'hs-sn-000038-2', 'hs-sn-000038-3'])
    expect(sn38.onsetQl.eq(Rational.of(42))).toBe(true)
    expect(sn38.offsetQl.eq(Rational.of(91, 2))).toBe(true) // 45.5
  })

  it('carries rests (cursor advance) without canonical spans', () => {
    // m4: frag2 12–14, half rest 14–16 → measure end 16
    const m4 = map.measures.find((m) => m.number === 4)!
    expect(m4.startQl.eq(Rational.of(12))).toBe(true)
    expect(m4.endQl.eq(Rational.of(16))).toBe(true)
    expect(map.spans.some((s) => s.exportIds.some((id) => id.startsWith('hs-rest')))).toBe(false)
  })

  it('reports 12 measure spans of 4 ql each, duration 48 ql', () => {
    expect(map.measures.length).toBe(12)
    for (const m of map.measures) {
      expect(m.endQl.sub(m.startQl).eq(Rational.of(4)), `m${m.number}`).toBe(true)
    }
    expect(map.durationQl.eq(Rational.of(48))).toBe(true)
  })

  it('produces identical canonical structure for the horn presentation', () => {
    const horn = buildSyncMap(hornXml)
    expect(horn.spans.map((s) => s.canonicalId)).toEqual(map.spans.map((s) => s.canonicalId))
    expect(horn.spans.map((s) => s.onsetQl.toString())).toEqual(
      map.spans.map((s) => s.onsetQl.toString()),
    )
  })

  it('extracts midi pitches for audio synthesis', () => {
    const pitches = pitchMidiByCanonical(concertXml)
    expect(pitches.get('sn-000001')?.midi).toBe(60) // C4
    expect(pitches.get('sn-000011')?.midi).toBe(66) // F#4
    expect(pitches.get('sn-000012')?.midi).toBe(58) // Bb3
    expect(pitches.size).toBe(40)
  })
})
