/**
 * Deterministic fixtures for UI-005.
 *
 * Both fixtures share the same committed MusicXML pair (generated by
 * scripts/gen-fixtures.mjs — 12 bars, 4/4, 100 BPM notated, 40 canonical
 * notes, ties at sn-000012/-000025/-000038, 2 rests). What differs is the
 * audio clock domain, i.e. which {@link TimeWarp} maps seconds ↔ ql:
 *
 *  - `steady`: fixed-BPM warp matching the notated tempo with a 0.4 s
 *    lead-in — the trivial-but-real alignment case.
 *  - `warped`: piecewise beat-map warp through per-measure anchors whose
 *    gaps widen (rallentando) — proves sync runs through the beat map,
 *    not through a constant-rate shortcut.
 *
 * Audio is synthesized in-app at load time from the canonical spans
 * (src/audio/synth.ts) — zero binary fixtures, fully offline.
 */
import concertXml from '../fixtures/sync_concert.musicxml?raw'
import hornXml from '../fixtures/sync_horn_in_f.musicxml?raw'
import { Rational } from './sync/rational'
import { TimeWarp, type BeatAnchor } from './sync/timewarp'

export type FixtureId = 'steady' | 'warped'
export type PitchView = 'concert' | 'horn'

export const SCORE_BPM = 100
export const LEAD_IN_SEC = 0.4

/**
 * Per-measure audio durations (seconds) for the `warped` fixture —
 * a deliberate rallentando from ~100 BPM toward ~57 BPM. Anchor k sits at
 * ql = 4k (measure boundary) and time = LEAD_IN + cumulative sum.
 */
export const WARPED_MEASURE_SECONDS = [
  2.4, 2.5, 2.7, 2.9, 3.0, 3.2, 3.3, 3.5, 3.6, 3.8, 4.0, 4.2,
] as const

/** Beat anchors for the warped fixture: one per measure boundary (ql 0..48). */
export function warpedAnchors(): BeatAnchor[] {
  const anchors: BeatAnchor[] = [{ timeSec: LEAD_IN_SEC, scorePosQl: Rational.of(0) }]
  let t = LEAD_IN_SEC
  WARPED_MEASURE_SECONDS.forEach((sec, i) => {
    t += sec
    anchors.push({ timeSec: t, scorePosQl: Rational.of(4 * (i + 1)) })
  })
  return anchors
}

export interface SyncFixtureDef {
  id: FixtureId
  /** Japanese label for the picker. */
  labelJa: string
  concertXml: string
  hornXml: string
  buildWarp: () => TimeWarp
}

export const FIXTURES: Record<FixtureId, SyncFixtureDef> = {
  steady: {
    id: 'steady',
    labelJa: '一定テンポ（100 BPM）',
    concertXml,
    hornXml,
    buildWarp: () => TimeWarp.fixedBpm(SCORE_BPM, LEAD_IN_SEC),
  },
  warped: {
    id: 'warped',
    labelJa: 'テンポ変化（リタルダンド）',
    concertXml,
    hornXml,
    buildWarp: () => TimeWarp.fromAnchors(warpedAnchors()),
  },
}

export function fixtureXml(id: FixtureId, view: PitchView): string {
  return view === 'horn' ? FIXTURES[id].hornXml : FIXTURES[id].concertXml
}
